import { TUser } from "../types"

const users: TUser[] = [
  {
    id: 1,
    email: 'gatocuantico@gmail.com',
    name: 'Gato',
    surname: 'Cuántico',
    username: 'quantacat',
    bio: 'Gato muy cuántico del mar de Quanta.',
    birthday: new Date(),
    avatar: require('../assets/example/avatar12.jpg'),
  },
  {
    id: 2,
    email: 'sonofbatman99@gmail.com',
    name: 'Hijoe',
    surname: 'Batman',
    username: 'sonofbatman',
    bio: 'El verdadero único e inigualable hijo e batman.',
    birthday: new Date(),
    avatar: require('../assets/example/avatar02.jpg'),
  },
  {
    id: 3,
    email: 'whipro99999@gmail.com',
    name: 'Programador',
    surname: 'Blanco99999',
    username: 'whipro99999',
    bio: 'Si dices supremacía blanca seguro vas preso por racista.',
    birthday: new Date(),
    avatar: require('../assets/example/avatar03.jpg'),
  },
  {
    id: 4,
    email: 'wilderyt@gmail.com',
    name: 'Wilder',
    surname: 'Perez',
    username: 'Wilburn',
    bio: 'De día Wilder de noche The Weekend.',
    birthday: new Date(),
    avatar: require('../assets/example/avatar01.jpg'),
  },
  {
    id: 5,
    email: 'huachimingo@gmail.com',
    name: 'Personalidad',
    surname: 'Wachu',
    username: 'wachiman',
    bio: 'Dicen que Watchmen es el origen de mi nombre. Yo digo lo contrario.',
    birthday: new Date(),
    avatar: require('../assets/example/avatar08.jpg'),
  },
  {
    id: 6,
    email: 'panteranegra@gmail.com',
    name: 'Wakanda',
    surname: '4ever',
    username: 'whitepantera',
    bio: 'Dicen que Watchmen es el origen de mi nombre. Yo digo lo contrario.',
    birthday: new Date(),
    avatar: require('../assets/example/avatar06.jpg'),
  },
  {
    id: 7,
    email: 'noviadepeter@gmail.com',
    name: 'Gwen',
    surname: 'Stacy64',
    username: 'GwenStacy',
    bio: 'A veces novia de Spiderman. A veces no.',
    birthday: new Date(),
    avatar: require('../assets/example/avatar10.jpg'),
  },
  {
    id: 8,
    email: 'supersayayin@gmail.com',
    name: 'Goku',
    surname: '12',
    username: 'kakaroto',
    bio: 'Hola! Soy Goku! Y estás leyendo esto con la voz de Mario Castañeda. Ten cuidado, él cobra!.',
    birthday: new Date(),
    avatar: require('../assets/example/avatar02.jpg'),
  },
  {
    id: 9,
    email: 'pinkshrimp@gmail.com',
    name: 'Camaron',
    surname: 'rosa',
    username: 'pinkshrimp',
    bio: 'Fan de Gura profesional.',
    birthday: new Date(),
    avatar: require('../assets/example/avatar11.jpg'),
  },
  {
    id: 10,
    email: 'RealBatman@gmail.com',
    name: 'Batman',
    surname: 'Original',
    username: 'Batman',
    bio: 'No le hagan caso al Batman falso. Yo si soy Batman.',
    birthday: new Date(),
    avatar: require('../assets/example/avatar02.jpg'),
  },
  {
    id: 11,
    email: 'GreatColombia@gmail.com',
    name: 'Simon',
    surname: 'Bolivar',
    username: 'liberator',
    bio: 'No estoy de acuerdo con que se ridiculice Venezuela, pero ella no ayuda.',
    birthday: new Date(),
    avatar: require('../assets/example/avatar09.jpg'),
  },
  {
    id: 12,
    email: 'sufferingu@gmail.com',
    name: 'Programador',
    surname: 'Front',
    username: 'suffering',
    bio: 'No me pagan lo suficiente por esto x2.',
    birthday: new Date(),
    avatar: require('../assets/example/avatar02.jpg'),
  },
]

export default users